appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GpooQ4jTtNOBwi7hpv6ZMQKAtbjY0XD8Sy0x79XngbM7dHQSf46A0X97YQINSRO6QQ0+E2FZ6KZ6Tt18hECuMFdmqXL/o5kgCeA3pnnVLKIBGtTNR8V06oV1ceEP/uWWh0rXAv4E/cVsqdmhwQ9iQtcv2xemXAjHOI03X9EwJQY0kv4/FudHYOnIbN7VvQpxJMWSQ+D80L2tq5fcSIvsLScSeNvBk5WRCoO+smfLqxoIQj+kXUejn9jcnJgzKcacdmqoar9xdVfXj8an/pibzWVKr28FTkvWd+LGnK1CS/tbSRPEdVKaP2aYL2BKOE4tzngKM7ys5RFnUAFbEYYgGqI859WTf4XehNuvRHwpsU/7fH9BIxVRCj33+a+xhMsSbwwirX0HtMD0zKwx86os7spLoZGO8z1HomkFkmjKUDvhKoVUWkDCb/zFt8UXetE/r7rhWOY3qxorKmm1BXjzlQ3OXoifQB+W0yCTQ4agntZd8Vzpou9gKOJBNhgrEOIh8mflyTFX5N99l3zD9Ew/ug9yrzCzSChKQ8CLP20uENKuhNVhr7v264/5b1W5cQGQVDYv+AVhkTBBzNNhGcV5satsE1PqjpIqh+VD6XeU2F6wI323tknJBy7QFXBdedGMN0jRhiI4Ak15rNKqorConjvDpj2jZGeHFIvb9ciogl0=}
conda_forge_output_validation: true
