travis:
  secure:
    BINSTAR_TOKEN: OKcPPs8jRcROhJol4Jwls6FLApgo6/D8PL9v9Ss9sTJqtT8GiYqXelKbXPPW7zGCSG+egddiA1bXs1KStynLssWVJnzjnMLpAuaZehhFI0ZtV9sRkx6Ws+ZJQkJwsuvMxQbk06dmuMiG76D+Bv/zdSV92A15RI2rE7vt9cRhLh/7w4PasYKYrcJL03nFeQfAhzY0GXdANiR8kCXtnykRFP2RTp4h9ADzicWxlybzsTJH0sM4pVm+1Aeu6q6PsHLLX6RDnFn2JnHFqb45DLyyYIli6bBEMijrKnfGrmTP5cDmStCh0SCEF59pc1JaaRzrgB5OM7GpSQ5QXKBlMsmBqmlhP/mZu6jUgny8zmdZzpEjH8MAfn46G/K9JGhlBluqI1lzYrqivSuLH3rBjOoMW3ZqYtB5RLjMXQka9ouMW9dc4Cpx2jZdPf7Y25JrP4uBftgxoKGkCKAsr+Ww91eAsJiSmWUi4u1ckakFh3Dvjr8DPwXjL8ICj/XHrcfzA/8yccc4PV2qGJ6OoFM8IqhdWZ9v55+8tjB+1Ql49jqSoZikvkI48etCaV3YzWoSV7uSSnteJLVR6DETfBMEKF8GXfvSui/6PWfOGQIau2fGn2n3FWGnhYH/3Dvt7zYn7lb8oKaP9fykfxF6arr4aVkqK5zW8mlV0rLnzhZZLaKwRjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
